### ISSUE TITLE
Configurable frequency per check

### ISSUE THREAD

**Issue by barrypitman** [newrelic/nri-nagios#121]
From what I can see in the docs, - nagios-config.yml

```
integrations:
  - name: nri-nagios
    env:
      CONCURRENCY: "1"
      SERVICE_CHECKS_CONFIG: /etc/newrelic-infra/integrations.d/nagios-service-checks.yml
    interval: 15s
```

the check interval can only be defined once and is shared between all checks in the nagios-service-checks.yml file. I have some checks that I would like to run more frequently than others. Is there any way that I can:

1. specify the interval on a per-check basis in the nagios-service-checks.yml file? (first prize)
2. Split the checks between multiple files, and provide a different interval per file.
